// 월별 "무엇을 기대할지" — 월 허브 상단 표. 서울 평년 기온(1991–2020 근사)·계절 특징·공휴일.
// 음력 공휴일은 연도별로 움직이므로 확실한 연도만 적고 나머지는 "lunar" 로 둔다. 매년 1월에 갱신.
export type MonthFacts = { weather: string; season: string; holidays: string };

export const MONTH_FACTS: MonthFacts[] = [
  { weather: 'Seoul around 2°C by day and −6°C at night; dry and clear, with occasional snow that rarely settles in the city.',
    season: 'Ice-fishing festivals in Gangwon, ski season at its best, and sunrise gatherings on the east coast on the 1st.',
    holidays: 'New Year’s Day (1 January). Seollal, the lunar new year, falls in late January or February depending on the year.' },
  { weather: 'Around 5°C by day and −3°C at night; the cold usually breaks in the last week.',
    season: 'Seollal closes small businesses for three or four days; ski slopes are still full; plum blossom starts on the south coast.',
    holidays: 'Seollal 2027: 6–9 February, including a substitute holiday on the 9th.' },
  { weather: 'Around 11°C by day and 2°C at night; windy, with yellow-dust days possible.',
    season: 'Plum and cornelian-cherry blossom in the south; cherry blossom reaches Jeju and Busan in the last week.',
    holidays: 'Independence Movement Day (1 March).' },
  { weather: 'Around 18°C by day and 8°C at night; mild, with some rain.',
    season: 'Cherry blossom peaks in Seoul in the first week — Yeouido, Seokchon Lake, Jinhae and Gyeongju all hold festivals.',
    holidays: 'No public holidays.' },
  { weather: 'Around 23°C by day and 13°C at night; with October, the best weather of the year.',
    season: 'Lotus lanterns for Buddha’s Birthday, rose and tea festivals, and long evenings outdoors.',
    holidays: 'Children’s Day (5 May) and Buddha’s Birthday, which follows the lunar calendar and usually lands in May.' },
  { weather: 'Around 27°C by day and 18°C at night; the monsoon (jangma) begins in the last week.',
    season: 'Firefly festivals in the clean-air counties, night markets, and the first beach openings.',
    holidays: 'Memorial Day (6 June).' },
  { weather: 'Around 29°C by day and 22°C at night; monsoon rain until mid-month, then humid heat.',
    season: 'Boryeong Mud Festival, water festivals in the cities, and programmes timed for the cool of the evening.',
    holidays: 'No public holidays.' },
  { weather: 'Around 30°C by day and 23°C at night; the hottest month, with typhoon risk late on.',
    season: 'Sea festivals on every coast, the big outdoor music festivals, and palace night openings.',
    holidays: 'Liberation Day (15 August).' },
  { weather: 'Around 26°C by day and 17°C at night; humidity drops after mid-month.',
    season: 'The Chuseok travel rush, the first autumn festivals, and early typhoons some years.',
    holidays: 'Chuseok follows the lunar calendar: 24–26 September in 2026, 14–16 September in 2027.' },
  { weather: 'Around 20°C by day and 10°C at night; dry, clear and, with May, the best month to travel.',
    season: 'The peak festival month. Foliage starts in the northern mountains mid-month; fireworks festivals in Seoul and Busan.',
    holidays: 'National Foundation Day (3 October) and Hangeul Day (9 October).' },
  { weather: 'Around 12°C by day and 2°C at night; the first frosts, still dry.',
    season: 'Foliage reaches Seoul and the south in the first two weeks; kimchi-making season; the illuminations switch on late in the month.',
    holidays: 'No public holidays.' },
  { weather: 'Around 4°C by day and −3°C at night; cold and dry, with the first real snow.',
    season: 'Christmas lights, the Seoul Lantern Festival, ski resorts fully open, and New Year’s Eve at Bosingak.',
    holidays: 'Christmas Day (25 December).' },
];
